name: Release

on:
  push:
    tags:
      - 'v*'  # e.g. v1.0.0

permissions:
  contents: write

jobs:
  prepare:
    name: Prepare source archives
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create source archives
        run: |
          zip -r go-source.zip go/
          zip -r csharp-source.zip csharp/

      - name: Upload source artifacts
        uses: actions/upload-artifact@v4
        with:
          name: source-archives
          path: |
            go-source.zip
            csharp-source.zip

  release:
    name: Publish release (requires approval)
    runs-on: ubuntu-latest
    needs: prepare
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/releases

    steps:
      - name: Download source artifacts
        uses: actions/download-artifact@v4
        with:
          name: source-archives
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
